# Generated by Django 5.1 on 2024-11-17 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_compra_total_alter_venta_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaventa',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.RenameField(
            model_name='facturaventa',
            old_name='impuestos',
            new_name='total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='numero_factura',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='fecha_suministro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
