# Generated by Django 5.1 on 2024-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_fecha_facturaventa_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='backend.DetalleVenta', to='backend.producto'),
        ),
    ]
